AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'test/**/*_test.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
