# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rulers", path: "../rulers"
gem "webrick", "~> 1.7"

group :development do
  gem "rerun", "~> 0.13.1"
end
